### ISSUE TITLE
安装你的note 出现一些异常

### ISSUE THREAD

**Issue by W2YN** [wowiwj/Note#1]
Script @php artisan package:discover handling the post-autoload-dump event returned with error code 255

php artisan key:generate
php artisan serve 
等等都无回显 环境也无法运行。。
我的php版本7.01的 mysql ,mysql  Ver 14.14 Distrib 5.7.12
环境vagrant

**Comment by wowiwj** [comment]
你好，readme安装方法已经更新，拉取最新的master分支的代码，重新安装试试呢
